spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5432/moviewatchlist_db
spring.datasource.username=whoami

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
